# Generated by Django 5.2.8 on 2025-12-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_profile'),
    ]

    operations = [
    ]
