# Generated by Django 5.2.8 on 2025-12-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_auto_20251206_2253'),
    ]

    operations = [
    ]
