# Generated by Django 5.2.8 on 2025-12-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_auto_20251207_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesacheckout',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mpesacheckout',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
