# Generated by Django 5.2.8 on 2025-12-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trader_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
